export const data = JSON.parse("{\"key\":\"v-7a968ea3\",\"path\":\"/learning-notes/java/primary/2.java%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html\",\"title\":\"Jav快速入门\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"Jav快速入门 java特性 1.java语言是面向对象的（oop） 3.跨平台性（一个便衣好的 .class 文件可以在多个系统下运行，中特性叫跨平台性） image-20230224001416416 4.java语言是解释性语言 ​\\t解释性语言：javascript，PHP，java ​\\t编译性语言：c、c++ 开发软件 editplus、notepad++、Sublime Text、IDEA、eclipse\"},\"headers\":[{\"level\":2,\"title\":\"java特性\",\"slug\":\"java特性\",\"link\":\"#java特性\",\"children\":[]},{\"level\":2,\"title\":\"开发软件\",\"slug\":\"开发软件\",\"link\":\"#开发软件\",\"children\":[]},{\"level\":2,\"title\":\"java运行机制及运行过程\",\"slug\":\"java运行机制及运行过程\",\"link\":\"#java运行机制及运行过程\",\"children\":[{\"level\":3,\"title\":\"机制：java核心机制-java 虚拟机 [ JVM （java virtual machine） ]\",\"slug\":\"机制-java核心机制-java-虚拟机-jvm-java-virtual-machine\",\"link\":\"#机制-java核心机制-java-虚拟机-jvm-java-virtual-machine\",\"children\":[]},{\"level\":3,\"title\":\"运行过程：\",\"slug\":\"运行过程\",\"link\":\"#运行过程\",\"children\":[]}]},{\"level\":2,\"title\":\"什么是JDK、JRE\",\"slug\":\"什么是jdk、jre\",\"link\":\"#什么是jdk、jre\",\"children\":[{\"level\":3,\"title\":\"JDK\",\"slug\":\"jdk\",\"link\":\"#jdk\",\"children\":[]},{\"level\":3,\"title\":\"JRE\",\"slug\":\"jre\",\"link\":\"#jre\",\"children\":[]},{\"level\":3,\"title\":\"JDK、JRE和JVM的关系\",\"slug\":\"jdk、jre和jvm的关系\",\"link\":\"#jdk、jre和jvm的关系\",\"children\":[]}]},{\"level\":2,\"title\":\"案例\",\"slug\":\"案例\",\"link\":\"#案例\",\"children\":[{\"level\":3,\"title\":\"需求说明：\",\"slug\":\"需求说明\",\"link\":\"#需求说明\",\"children\":[]},{\"level\":3,\"title\":\"开发步骤\",\"slug\":\"开发步骤\",\"link\":\"#开发步骤\",\"children\":[]},{\"level\":3,\"title\":\"练习\",\"slug\":\"练习\",\"link\":\"#练习\",\"children\":[]}]},{\"level\":2,\"title\":\"2. java 执行流程分析\",\"slug\":\"_2-java-执行流程分析\",\"link\":\"#_2-java-执行流程分析\",\"children\":[{\"level\":3,\"title\":\"什么是编译？\",\"slug\":\"什么是编译\",\"link\":\"#什么是编译\",\"children\":[]},{\"level\":3,\"title\":\"什么是运行？\",\"slug\":\"什么是运行\",\"link\":\"#什么是运行\",\"children\":[]},{\"level\":3,\"title\":\"java程序开发注意事项！\",\"slug\":\"java程序开发注意事项\",\"link\":\"#java程序开发注意事项\",\"children\":[]},{\"level\":3,\"title\":\"Java开发细节说明\",\"slug\":\"java开发细节说明\",\"link\":\"#java开发细节说明\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.75,\"words\":825},\"filePathRelative\":\"learning-notes/java/primary/2.java快速入门.md\",\"excerpt\":\"<h1> Jav快速入门</h1>\\n<h2> java特性</h2>\\n<p>1.java语言是面向对象的（oop）</p>\\n<p>3.跨平台性（一个便衣好的 .class 文件可以在多个系统下运行，中特性叫跨平台性）</p>\\n<figure><figcaption>image-20230224001416416</figcaption></figure>\\n<p>4.java语言是解释性语言</p>\\n<p>​\\t解释性语言：javascript，PHP，java</p>\\n<p>​\\t编译性语言：c、c++</p>\\n<h2> 开发软件</h2>\\n<p>editplus、notepad++、Sublime Text、IDEA、eclipse</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
